export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import NavBar from "../components/NavBar";
// import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main>{children}</main>
      </body>
    </html>
  )
}
